import React from 'react'
import './css/Home.css'
const Home = () => {
  return (
    <div className='home-container'>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Reiciendis voluptates nihil ullam voluptatem dolor amet. Quisquam quis molestiae pariatur nam dolor, voluptatum eaque. Recusandae delectus explicabo asperiores corrupti, ratione ducimus temporibus vitae nisi soluta.
    Lorem ipsum, dolor sit amet consectetur adipisicing elit. Reiciendis minus autem impedit maiores debitis ut ad facere incidunt officiis ullam, omnis nihil dolores ea iste, inventore eius, vitae sapiente! Sed quia exercitationem voluptatem. Omnis ipsam maxime ad distinctio aspernatur nisi earum praesentium eligendi, error veritatis sunt dignissimos! Optio culpa expedita alias molestias eum accusamus ea fugit laudantium nam doloremque quo cupiditate iusto doloribus, laboriosam incidunt! Modi possimus est quod eveniet, quo aperiam ea. Hic cupiditate in natus et nemo vel maiores, dicta sit, quaerat corrupti autem omnis dolore vero dolorem iure magni perferendis. Quisquam itaque earum corporis repellendus similique impedit nisi ducimus. Quod tempore mollitia, veniam repellendus sit voluptates quam unde libero exercitationem reprehenderit vel ipsam itaque illo voluptatem esse est quae eaque fuga, quas nulla! Reprehenderit ea facilis recusandae dignissimos porro et voluptatibus ut iusto nemo suscipit. Nisi repellat, quos aut nam, repellendus voluptate ut asperiores laboriosam ipsam nulla animi aperiam voluptatum velit dicta provident tenetur rem sunt incidunt. Numquam explicabo harum aperiam eum praesentium omnis, autem vero possimus cumque ea quibusdam, sed quis consectetur molestiae sapiente adipisci nisi recusandae, hic labore. In consequatur, ducimus quidem dolore vel neque, soluta deleniti tenetur nulla eligendi recusandae officiis ratione. Inventore error sit vero neque expedita est animi maiores corporis at eius, odio velit temporibus nisi fugit voluptas deserunt voluptates natus quia laboriosam voluptatem, similique dolores dolore non! Quod omnis veritatis eligendi ullam ex quasi earum obcaecati dolore doloremque! Laboriosam at totam provident reiciendis labore, culpa debitis nam sequi dolore reprehenderit doloremque?
    </div>
  )
}

export default Home